"""empty message

Revision ID: e2f54ef46ce3
Revises: None
Create Date: 2018-04-16 22:44:32.354369

"""

# revision identifiers, used by Alembic.
revision = 'e2f54ef46ce3'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('library',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('isbn', sa.String(length=50), nullable=True),
    sa.Column('link', sa.String(length=100), nullable=True),
    sa.Column('editura', sa.String(length=100), nullable=True),
    sa.Column('price', sa.String(length=20), nullable=True),
    sa.Column('img', sa.String(length=100), nullable=True),
    sa.Column('library_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['library.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('sqlite_sequence')
    op.drop_table('books_librarie_big')
    op.drop_table('books_carturesti')
    op.drop_table('books_main')
    op.drop_table('books_librarie_small')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books_librarie_small',
    sa.Column('book_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('isbn', sa.VARCHAR(length=50), nullable=True),
    sa.Column('link', sa.VARCHAR(length=100), nullable=True),
    sa.Column('price', sa.VARCHAR(length=20), nullable=True),
    sa.Column('img', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('book_id')
    )
    op.create_table('books_main',
    sa.Column('book_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('author', sa.VARCHAR(length=100), nullable=True),
    sa.Column('isbn', sa.VARCHAR(length=50), nullable=True),
    sa.Column('bar_code', sa.VARCHAR(length=50), nullable=True),
    sa.Column('editura', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('book_id')
    )
    op.create_table('books_carturesti',
    sa.Column('book_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('author', sa.VARCHAR(length=100), nullable=True),
    sa.Column('isbn', sa.VARCHAR(length=50), nullable=True),
    sa.Column('link', sa.VARCHAR(length=100), nullable=True),
    sa.Column('editura', sa.VARCHAR(length=100), nullable=True),
    sa.Column('price', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('book_id')
    )
    op.create_table('books_librarie_big',
    sa.Column('book_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('isbn', sa.VARCHAR(length=50), nullable=True),
    sa.Column('link', sa.VARCHAR(length=100), nullable=True),
    sa.Column('price', sa.VARCHAR(length=20), nullable=True),
    sa.Column('img', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('book_id')
    )
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    op.drop_table('books')
    op.drop_table('users')
    op.drop_table('library')
    # ### end Alembic commands ###
